Repository kubeshop/kusk-gateway, pull requests merged in 2022-03, with the labels that each got.

#244 Removed CertManager dependency, added local certs generation for the webhook server
  Makefile
  README.md
  build/manager/Dockerfile
  build/manager/Dockerfile-debug
  cmd/manager/main.go
  config/certmanager/certificate.yaml
  config/certmanager/kustomization.yaml
  config/certmanager/kustomizeconfig.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_apis.yaml
  config/crd/patches/cainjection_in_envoyfleet.yaml
  config/crd/patches/cainjection_in_staticroutes.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/webhookcainjection_patch.yaml
  config/local/kustomization.yaml
  config/rbac/role.yaml
  development/cluster/create-cluster.sh
  development/cluster/create-env.sh
  docs/installation.md
  docs/local-installation.md
  internal/agent/management/manager.go
  internal/webhooks/certs.go
Labels: area/operator, kind/enhancement

#245 Speed Up local development
  Makefile
  build/agent/Dockerfile
  build/agent/Dockerfile-debug
  build/manager/Dockerfile
  build/manager/Dockerfile-debug
  development/cluster/create-cluster.sh
  development/cluster/create-env.sh
  development/cluster/delete-env.sh
  development/goproxy/README.md
  development/goproxy/docker-compose.yaml
Labels: kind/enhancement

#275 KGW CLI doc
  docs/kgw-cli.md
  mkdocs.yml
Labels: area/docs
