Repository kubeshop/kusk-gateway, pull requests merged in 2022-02, with the labels that each got.

#215 Differentiate between InternalServer and BadRequest webhook responses
  api/v1alpha1/envoyfleet_webhook.go
Labels: kind/bug

#219 Project layout refactoring
  .github/workflows/release.yaml
  Makefile
  api/v1alpha1/api_webhook.go
  api/v1alpha1/envoyfleet_webhook.go
  api/v1alpha1/staticroute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/manager/Dockerfile
  build/manager/Dockerfile-debug
  cmd/manager/main.go
  internal/cert/cert.go
  internal/cert/cert_test.go
  internal/controllers/api_controller.go
  internal/controllers/config_manager.go
  internal/controllers/envoyfleet_controller.go
  internal/controllers/envoyfleet_resources.go
  internal/controllers/helpers.go
  internal/controllers/parser.go
  internal/controllers/staticroute_controller.go
  internal/controllers/suite_test.go
  internal/envoy/config/config.go
  internal/envoy/config/hcm.go
  internal/envoy/config/listener.go
  internal/envoy/config/logging.go
  internal/envoy/manager/callbacks.go
  internal/envoy/manager/logger.go
  internal/envoy/manager/manager.go
  internal/envoy/types/cors.go
  internal/envoy/types/cors_test.go
  internal/envoy/types/headermatcher.go
  internal/envoy/types/headermatcher_test.go
  internal/envoy/types/redirect.go
  internal/envoy/types/redirect_test.go
  internal/envoy/types/routematcher.go
  internal/envoy/types/routematcher_test.go
  internal/envoy/types/virtualhost.go
  internal/envoy/types/virtualhost_test.go
  internal/k8sutils/utils.go
  internal/local/local.go
  internal/options/cors.go
  internal/options/host.go
  internal/options/options.go
  internal/options/path.go
  internal/options/quos.go
  internal/options/ratelimit.go
  internal/options/redirect.go
  internal/options/rewrite.go
  internal/options/static_options.go
  internal/options/upstream.go
  internal/options/validation.go
  internal/spec/extension.go
  internal/spec/extension_test.go
  internal/spec/spec.go
  internal/spec/spec_test.go
  internal/validation/error.go
  internal/validation/proxy.go
Labels: kind/enhancement, area/ci

#221 Remove local mode as not maintained
  cmd/manager/main.go
  docker-compose.yaml
  go.mod
  internal/local/local.go
Labels: kind/enhancement

#223 Mocking service
  .github/workflows/release.yaml
  Makefile
  api/v1alpha1/api_webhook.go
  api/v1alpha1/envoyfleet_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/helper/Dockerfile
  build/helper/Dockerfile-debug
  cmd/helper/main.go
  cmd/manager/main.go
  config/crd/bases/gateway.kusk.io_envoyfleet.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/service.yaml
  development/cluster/create-env.sh
  development/testing/README.md
  development/testing/manifests/api.yaml
  development/testing/postman/api.postman_collection.json
  development/testing/runtest.sh
  internal/controllers/config_manager.go
  internal/controllers/envoyfleet_resources.go
  internal/controllers/parser.go
  internal/helper/httpserver/handlers.go
  internal/helper/httpserver/middleware.go
  internal/helper/httpserver/server.go
  internal/helper/management/convertion.go
  internal/helper/management/management.pb.go
  internal/helper/management/management.proto
  internal/helper/management/management_grpc.pb.go
  internal/helper/management/manager.go
  internal/helper/mocking/config.go
  internal/helper/mocking/response.go
  internal/k8sutils/utils.go
  internal/options/mocking.go
  internal/options/options.go
Labels: area/operator, kind/feature

#232 Add mocking docs
  docs/extension.md
Labels: area/docs

#237 Rename helper to agent
  .github/workflows/release.yaml
  Makefile
  api/v1alpha1/envoyfleet_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  build/agent/Dockerfile
  build/agent/Dockerfile-debug
  cmd/agent/main.go
  cmd/manager/main.go
  config/crd/bases/gateway.kusk.io_envoyfleet.yaml
  config/default/manager_webhook_patch.yaml
  config/manager/service.yaml
  development/testing/README.md
  development/testing/runtest.sh
  internal/agent/httpserver/handlers.go
  internal/agent/httpserver/middleware.go
  internal/agent/httpserver/server.go
  internal/agent/management/convertion.go
  internal/agent/management/management.pb.go
  internal/agent/management/management.proto
  internal/agent/management/management_grpc.pb.go
  internal/agent/management/manager.go
  internal/agent/mocking/config.go
  internal/agent/mocking/response.go
  internal/controllers/config_manager.go
  internal/controllers/envoyfleet_resources.go
  internal/controllers/helpers.go
  internal/controllers/parser.go
  internal/spec/spec.go
Labels: kind/enhancement

#238 Handling Mocking media types
  development/testing/manifests/api.yaml
  development/testing/postman/api.postman_collection.json
  docs/extension.md
  go.mod
  go.sum
  internal/agent/httpserver/handlers.go
  internal/agent/httpserver/negotiator.go
  internal/agent/httpserver/negotiator_test.go
  internal/agent/mocking/config.go
  internal/controllers/parser.go
Labels: area/operator, kind/enhancement
