Repository kubeshop/kusk-gateway, pull requests merged in 2022-01, with the labels that each got.

#167 Add websockets support
  Makefile
  api/v1alpha1/staticroute_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/gateway.kusk.io_staticroutes.yaml
  controllers/parser.go
  development/cluster/create-env.sh
  examples/websocket/README.md
  examples/websocket/backend.yaml
  examples/websocket/websocket-api.yaml
  examples/websocket/websocket-staticroute.yaml
  options/options.go
  options/static_options.go
Labels: area/operator, kind/feature

#175 Fix KGWM log entries from default Epoch to ISO8601
  go.mod
  main.go
Labels: kind/bug

#182 Fix panic if RewriteRegex struct is nil in StaticRoute resource
  controllers/parser.go
Labels: kind/bug

#159 Alpha.2 prerelase fixes
  README.md
  docs/customresources/api.md
  docs/customresources/envoyfleet.md
  docs/customresources/staticroute.md
  docs/extension.md
  docs/installation.md
  docs/local-installation.md
  docs/observability.md
  docs/todomvc.md
  docs/troubleshooting.md
  examples/todomvc/spec/todospec.yaml
  mkdocs.yml
Labels: area/docs

#197 Fix checking CRD/RBAC resources changes between the 2 last tags
  .github/workflows/release.yaml
Labels: kind/bug, area/ci

#198 Add better documentation
  README.md
  docs/arch.md
  docs/index.md
  docs/roadmap.md
  mkdocs.yml
Labels: area/docs, kind/enhancement

#206 Fix for the paths rewrite override
  controllers/parser.go
Labels: area/operator, kind/bug
